# Generated by Django

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_giao_dich', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Mã giao dịch')),
                ('id_nguoi_gui', models.CharField(db_index=True, max_length=50, verbose_name='ID người gửi')),
                ('id_nguoi_nhan', models.CharField(db_index=True, max_length=50, verbose_name='ID người nhận')),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền giao dịch')),
                ('so_du_tai_khoan', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số dư tài khoản')),
                ('ngay_gio_giao_dich', models.DateTimeField(db_index=True, verbose_name='Ngày giờ giao dịch')),
                ('loai_giao_dich', models.CharField(choices=[('CHUYEN_KHOAN', 'Chuyển khoản'), ('THANH_TOAN', 'Thanh toán'), ('RUT_TIEN', 'Rút tiền'), ('GUI_TIEN', 'Gửi tiền'), ('MUA_SAM', 'Mua sắm'), ('KHAC', 'Khác')], db_index=True, max_length=20, verbose_name='Loại giao dịch')),
                ('trang_thai_giao_dich', models.CharField(choices=[('HOAN_THANH', 'Hoàn thành'), ('CHO_XU_LY', 'Chờ xử lý'), ('THAT_BAI', 'Thất bại'), ('HUY_BO', 'Hủy bỏ')], default='HOAN_THANH', max_length=20, verbose_name='Trạng thái giao dịch')),
                ('noi_dung_giao_dich', models.TextField(blank=True, verbose_name='Nội dung giao dịch')),
                ('co_gian_lan', models.BooleanField(db_index=True, default=False, verbose_name='Cờ gian lận')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Các giao dịch',
                'ordering': ['-ngay_gio_giao_dich'],
            },
        ),
        migrations.CreateModel(
            name='DuDoanGianLan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_gian_lan', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Điểm gian lận')),
                ('du_doan_gian_lan', models.BooleanField(default=False, verbose_name='Dự đoán gian lận')),
                ('phien_ban_mo_hinh', models.CharField(max_length=50, verbose_name='Phiên bản mô hình')),
                ('ngay_du_doan', models.DateTimeField(auto_now_add=True, verbose_name='Ngày dự đoán')),
                ('giao_dich', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='du_doan_gian_lan', to='transactions.transaction', verbose_name='Giao dịch')),
            ],
            options={
                'verbose_name': 'Dự đoán gian lận',
                'verbose_name_plural': 'Các dự đoán gian lận',
            },
        ),
        migrations.CreateModel(
            name='CumGiaoDich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cum', models.IntegerField(db_index=True, verbose_name='ID cụm')),
                ('nhan_cum', models.CharField(blank=True, max_length=100, verbose_name='Nhãn cụm')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('giao_dich', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cum_giao_dich', to='transactions.transaction', verbose_name='Giao dịch')),
            ],
            options={
                'verbose_name': 'Cụm giao dịch',
                'verbose_name_plural': 'Các cụm giao dịch',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ngay_gio_giao_dich', 'so_tien'], name='transaction_ngay_gi_066f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['id_nguoi_gui', 'ngay_gio_giao_dich'], name='transaction_id_nguo_ff8b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['co_gian_lan', 'ngay_gio_giao_dich'], name='transaction_co_gian_25c8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='dudoangianlan',
            index=models.Index(fields=['du_doan_gian_lan', 'diem_gian_lan'], name='transaction_du_doan_4c6e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='cumgiaodich',
            index=models.Index(fields=['id_cum'], name='transaction_id_cum_c37a25_idx'),
        ),
    ]