# Generated by Django 5.2.2 on 2025-06-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cumgiaodich',
            new_name='transaction_id_cum_4a5fe7_idx',
            old_name='transaction_id_cum_c37a25_idx',
        ),
        migrations.RenameIndex(
            model_name='dudoangianlan',
            new_name='transaction_du_doan_19230b_idx',
            old_name='transaction_du_doan_4c6e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_ngay_gi_0ad6db_idx',
            old_name='transaction_ngay_gi_066f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_id_nguo_e3a181_idx',
            old_name='transaction_id_nguo_ff8b7c_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_co_gian_3fe23e_idx',
            old_name='transaction_co_gian_25c8dc_idx',
        ),
    ]
